FROM agrigorev/zoomcamp-model:mlops-2024-3.10.13-slim

RUN pip install --no-cache-dir pipenv

WORKDIR /app

COPY Pipfile Pipfile.lock ./

RUN pipenv install --system --deploy

COPY score.py ./

ENTRYPOINT ["python", "score.py"]